Some refactoring and doc fixes
kislball/goocord pull request #2
Opened 2021-06-28 13:55 UTC by FedorLap2006

2021-06-28 14:00 UTC, kislball requested changes
Everything is nice, but there is a moment I don't understand

2021-06-28 14:06 UTC, FedorLap2006 commented on cache.go
> +	ns.data = make(map[string]interface{})
It's more clear and less confusing. Also it's quite the standard to initialise an empty map like that.

2021-06-29 12:59 UTC, kislball commented
Have you done `go vet` on the project?

2021-06-29 13:21 UTC, kislball reviewed
NIce, merging

2021-06-29 13:22 UTC, kislball approved these changes
Nice!

2021-06-29 13:22 UTC, merged